name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      device:
        description: "Kernel device target"
        required: true
        type: choice
        default: "gts8uwifi"
        options:
          - gts8uwifi
          - gts8wifi

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ben443/Samsung_Kernel_sm8450_common_gts8x
          #kernel-dir: msm-4.19
          kernel-branch: msm-kernel_Nethunter
          config: ${{ inputs.device }}-waipio_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 14
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true
